### PR TITLE
First draft of `slope_sizing_function`

### PR DESCRIPTION
**Pull request by ml14je**
Attempt at translating `slope_sizing_function` from `OceanMesh2D.m` into Python. The coordinate wrapping has not been tested, and there could be issues with the filtering (`filterfx.py`, which is merely a translation of MatLab's `filt2.m`. It's not perfect, but I am certain it can be improved upon.

There was a quick change to the `README.md` which updated the user on how to use `fix_mesh` without an error being thrown. Furthermore, the kwarg in `compute_minimum` of `grid.py` meant that the grid now extrapolates values, particularly along a boundary.

### CODE REVIEW

**Comment by krober10nd** [comment]
Okay, its a bit hard to see what changed and what did not. Are you using a linter here? 

I would recommend to please run `flake8` and `black` on all the files you've touched. This way we can see what changed exactly on the line-by-line report.

**Comment by krober10nd** [comment]
@ml14je here are some current issues from `flake8`: 

oceanmesh/filterfx.py:83:5: F811 redefinition of unused 'np' from line 10
oceanmesh/edgefx.py:389:1: C901 'slope_sizing_function' is too complex (30)
oceanmesh/edgefx.py:508:15: E712 comparison to True should be 'if cond is True:' or 'if cond:'
oceanmesh/edgefx.py:509:20: E401 multiple imports on one line
oceanmesh/edgefx.py:541:13: E741 ambiguous variable name 'I'
oceanmesh/edgefx.py:610:9: F841 local variable 'time_taken' is assigned to but never used
oceanmesh/edgefx.py:620:21: F821 undefined name 'sqrt'
oceanmesh/__init__.py:9:1: F401 'oceanmesh.edgefx.slope_sizing_function' imported but unused
oceanmesh/__init__.py:19:1: F401 'oceanmesh.filterfx.filt2' imported but unused
oceanmesh/__init__.py:25:1: F401 'oceanmesh.signed_distance_function.create_bbox' imported but unused

**Comment by ml14je** [comment]
I'm terribly sorry. This is new for me. I can make those edits. Am I correct in saying that Flake8 and Black ar Python modules?

**Comment by krober10nd** [comment]
> I'm terribly sorry. This is new for me. I can make those edits. Am I correct in saying that Flake8 and Black ar Python modules?

ah no worries. Thank you for the contribution! Yes, they are both linters. `oceanmesh` uses them for consistency. You just need to run `flake8` and fix the messages. `black` is done automatically vis a bot here when you open a PR.

**Comment by ml14je** [comment]
> s a README example could be added showin

I can certainly do so once I have moved the filtering into the `grid` class.

**Comment by krober10nd** [comment]
Alright, looks like we also need to rebase with master before going any further here as there's some developments on master that do not appear here. I can do that tomorrow. I also need to hook up your `filt2` function to the bathymetric gradient sizing function.

**Comment by krober10nd** [comment]
@ml14je can you provide a test of this functionality so we can wrap this up please?

**Comment by ml14je** [comment]
I think I have given a test case (see tests/test_bathymetric_gradient_function.py) but needs work. Individual edge functions works well, but when combined, there appears to be an error whereby the edge_function isn't being smoothed via the enforce_mesh_gradation.

**Review by krober10nd — APPROVED** [review]

**Pull request merged**
