### PR TITLE
mesh "cleaning"

### PR DESCRIPTION
**Pull request by krober10nd**
Working on adding mesh cleaning abilities that were available in the MATLAB verison.
* Added the equivalent of [`make_mesh_boundaries_traversable.m`](https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/utilities/Make_Mesh_Boundaries_Traversable.m) and two tests to test the delete interior cells and delete exterior cell routines.

### CODE REVIEW

**Comment by krober10nd** [comment]
Okay, here we go: 

```
 import meshio
 
 from oceanmesh import (
     Shoreline,
     distance_sizing_function,
     signed_distance_function,
     generate_mesh,
     make_mesh_boundaries_traversable,
 )
 
 fname = "datasets/gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp"
 
 bbox, h0 = (-75.000, -70.001, 40.0001, 41.9000), 1e3
 
 shore = Shoreline(fname, bbox, h0)
 
 cell_size = distance_sizing_function(shore, max_size=5e3 / 111e3)
 
 domain = signed_distance_function(shore)
 
 points, cells = generate_mesh(
     domain=domain, cell_size=cell_size, h0=1e3 / 111e3, max_iter=50
 )
 
 points, cells = make_mesh_boundaries_traversable(points, cells)
 
 meshio.write_points_cells(
     "simple_new_york_cleaned.vtk",
     points,
     [("triangle", cells)],
     file_format="vtk",
 )
```
* before cleaning 

bad_b4

* after cleaning
after

**Comment by krober10nd** [comment]
`numba` is no longer building on CircleCI for a change. Think I'll just switch to the latest pure Python [`inpoly-python`](https://github.com/dengwirda/inpoly-python)

**Comment by WPringle** [comment]
I like how it's using the python inpoly you made with Darren (for some reason called "inpoly2")

**Review by WPringle — APPROVED** [review]

**Comment by krober10nd** [comment]
> I like how it's using the python inpoly you made with Darren (for some reason called "inpoly2")

Yea, because it the algorithm currently only works in 2d. It is quite fast.

**Pull request merged**
