### PR TITLE
adding gradient limiting

### PR DESCRIPTION
**Pull request by krober10nd**
* enables one to gradient limit a mesh size function 
```
 import oceanmesh as om
 import numpy as np
 
 fname = "GSHHS_shp/f/GSHHS_f_L1.shp"
 bbox, min_edge_length = (-75, -65.0, 45.0, 50.00), 1e3
 shore = om.Shoreline(fname, bbox, min_edge_length)
 distance_edge_length = om.distance_sizing_function(
     shore, max_edge_length=50e3, rate=0.35
 )
 distance_edge_length.plot(show=False, file_name="d15.png")
 d = om.enforce_mesh_gradation(distance_edge_length, gradation=0.05)
 d.plot(show=False, file_name="d05.png")
 ```

### CODE REVIEW

**Comment by WPringle** [comment]
Not sure it's working correctly. Here is output I got from the `test_grade.py`:

```
def test_grade():
    fname = "gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp"

    bbox, min_edge_length = (-75.000, -70.001, 40.0001, 41.9000), 1e3

    shore = om.Shoreline(fname, bbox, min_edge_length)

    edge_length = om.distance_sizing_function(shore, rate=0.35)
    edge_length.plot(show=False, file_name="test_grade_edgelength_orig.png"):
```

image

```
    test_edge_length = om.enforce_mesh_gradation(edge_length, gradation=0.20)
    test_edge_length.plot(show=False, file_name="test_grade_edgelength.png"):
```
image

So it seems to do something to decrease the maximum edgelength size (note the colormap axis differences), but these these strange vertical streaks are introduced.

**Comment by krober10nd** [comment]
Yes, unlike in the matlab version, I don't incorporate diagonals into the gradient limiting so it can only limit along x and y axis.

 If you want to implement that, please feel free. 

Those packages are standard on Linux distributions. If you're on a cluster you might have to load the modules but I wouldn't recommend installing them as they can effect the functionality of other programs on a typical PC/Mac/Linux machine.

**Comment by WPringle** [comment]
what about mentioning can get gmp from conda (https://anaconda.org/conda-forge/gmp/). That might work. I think it is necessary for most people on hpc, either get that or load from module if it is installed.

**Comment by WPringle** [comment]
I think the grader needs to have the diagonals implemented. Not sure this is usable in the current form.

**Comment by WPringle** [comment]
Cool thanks, so I get the following edgelength function and mesh for updated version.
image
image

Obviously the mesh looks great, but I must admit I'm still a bit surprised by how the edgelength function looks. I may try to do some deeper investigation of the smoother code in more detail over the weekend if that be OK? It might just be the test case and some kind of optical illusion, but just to be sure.

**Comment by krober10nd** [comment]
yea that's fine. I've really never taken a deep look at this grader that much. Maybe we'll find new errors.

**Comment by krober10nd** [comment]
This is a more comprehensive example, it took 684.6211273670197 seconds.

```
 import time
 
 import matplotlib.pyplot as plt
 import matplotlib.tri as tri
 
 from oceanmesh import (
     DEM,
     Shoreline,
     compute_minimum,
     delete_faces_connected_to_one_face,
     distance_sizing_function,
     generate_mesh,
     make_mesh_boundaries_traversable,
     signed_distance_function,
     wavelength_sizing_function,
     enforce_mesh_gradation,
 )
 
 t1 = time.time()
 fname = "GSHHS_shp/f/GSHHS_f_L1.shp"
 
 bbox, min_edge_length = (-80, -60.0, 35.0, 50.00), 1e3
 
 shore = Shoreline(fname, bbox, min_edge_length)
 
 fname = "/Volumes/KeithJaredR/MESHING_DATASETS/DEMS/SRTM15+V2.1.nc"
 
 # Read and visualize the geospatial data
 dem = DEM(fname, bbox)
 ax = dem.plot(hold=True, coarsen=10, title="SRTM + GSHHS", cbarlabel="meters")
 shore.plot(ax=ax, file_name="geospatial.png", show=False)
 
 # Make resolution follow depth
 distance_edge_length = distance_sizing_function(shore, max_edge_length=50e3)
 distance_edge_length.plot(
     coarsen=2,
     title="Distance sizing function",
     cbarlabel="degrees",
     file_name="distance_sizing_function.png",
     show=False,
 )
 
 # Vary mesh resolution according to the wavelength/wl of the M2 tidal constitutent
 wavelength_edge_length = wavelength_sizing_function(dem, wl=100)
 wavelength_edge_length.plot(
     coarsen=10,
     title="Wavelength sizing function",
     cbarlabel="degrees",
     file_name="wavelength_sizing_function.png",
     show=False,
 )
 
 # Compute the minimum of all mesh size functions
 edge_length = compute_minimum([distance_edge_length, wavelength_edge_length])
 
 edge_length = enforce_mesh_gradation(edge_length)
 
 edge_length.plot(
     title="Minimum edge length",
     file_name="total_mesh_size.png",
     cbarlabel="degrees",
     show=False,
 )
 
 # Define the meshing domain via an implicit function
 domain = signed_distance_function(shore)
 
 # Generate the mesh
 points, cells = generate_mesh(domain, edge_length, verbose=2, max_iter=100)
 
 # remove degenerate mesh faces and other common problems in the mesh
 points, cells = make_mesh_boundaries_traversable(points, cells)
 
 points, cells = delete_faces_connected_to_one_face(points, cells)
 
 print(f"Finished in {time.time() - t1} seconds")
 
 # plot
 fig, ax = plt.subplots()
 ax.set_aspect("equal")
 triang = tri.Triangulation(points[:, 0], points[:, 1], cells)
 ax.triplot(triang, "-", lw=1)
 plt.show()
```

with_wavelength_2
with_wavelength

**Comment by WPringle** [comment]
@krober10nd I made a suggested change to the HamiltonJacobi as committed, but was giving an error on compile which I couldn't work out. 

I think there is also another possibility of error, but not sure. The index starting from 1 is used in ind2sub and sub2ind, but what about the `ffun_s` variable. Is it in 0-index or 1-index? Should the sub2ind values be converted back to 0-index?

**Comment by krober10nd** [comment]
Okay appears to be working now as expected.
total_mesh_size
wavelength_sizing_function
distance_sizing_function

**Review by WPringle — APPROVED** [review]
Worked on my end too. I think the gradation is good for now.

**Pull request merged**
