### PR TITLE
 enforcing size bounds

### PR DESCRIPTION
**Pull request by krober10nd**
* as a function of depth. #29

### CODE REVIEW

**Comment by krober10nd** [comment]
Okay, might want to do some grading on that but the idea is this

```
 import oceanmesh as om
 
 demf = "/Users/Keith/junk/OceanMesh2D/datasets/SRTM15_V2.3.nc"
 shof = "gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp"
 
 bbox, min_edge_length = (-75.000, -70.001, 40.0001, 41.9000), 1e3
 
 dem = om.DEM(demf, bbox)
 
 sho = om.Shoreline(shof, bbox, min_edge_length)
 
 edge_length = om.distance_sizing_function(sho)
 
 bounds = [[2000.0, 3000.0, -250, -100], [1000.0, 1500.0, -100, -50]]
 edge_length = om.enforce_mesh_size_bounds_depth(edge_length, dem, bounds)
 
 edge_length.plot(vmin=1e3 / 111e3, vmax=4e3 / 111e3)

```

Figure_1

**Comment by krober10nd** [comment]
With the two size bounds and then a grade. 

Figure_2

**Comment by krober10nd** [comment]
Will have to update the build system to be like it is in SeismicMesh. Problems with the installation of SeismicMesh.

**Comment by WPringle** [comment]
depth means `depth` or `elevation` relative to datum? need to make the orientation clear.

**Comment by krober10nd** [comment]
`water depth` which I refer to as `depth` (assuming still-water) all relative to whatever datum the DEM was made to.

**Comment by WPringle** [comment]
it looks like in the example you use a negative value to indicate underwater, which I think really should be defined as elevation rather than depth (which would be positive underwater). In any case, let's add some explanation that it is the same definition as the DEM (negative downwards towards the earth center).

**Comment by WPringle** [comment]
and then finally, I suggest to add the example usage of this to the test suite.

**Comment by krober10nd** [comment]
alright switched depth -> elevation, updated docstring, added a test.

**Review by WPringle — APPROVED** [review]
LGTM

**Pull request merged**
