### PR TITLE
Remove nan in nodes for in_poly2

### PR DESCRIPTION
**Pull request by alcoat**
with numpy=1.23.0 and inpoly=0.2.0, the nodes can't have nan values when calling in_poly2

### CODE REVIEW

**Comment by krober10nd** [comment]
What changed in numpy that stopped nans working in inpoly I wonderr? I can change inpoly too

**Comment by krober10nd** [comment]
FYI https://github.com/rasterio/rasterio/issues/2333

**Comment by krober10nd** [comment]
Thank you for putting this together. Unfortunately while the tests do technically pass and do not produce fatal errors, when you visualize some of their outputs, it shows that the change to avoid passing nans to inpoly are creating new issues. This does not happen on the main branch. 

More generally, I'd like to figure out why inpoly stops working with 3.10a. 

For example visualizing test_irregular_domain.py or test_multiscale.py 

image

**Comment by alcoat** [comment]
Hi, I found a solution to this issue by removing duplicate points in the shoreline ! I will prepare the fix.

**Comment by krober10nd** [comment]
Excellent work @alcoat. I ran the tests locally with other versions of Python and things have worked out. So I'm okay with this as is.

**Review by krober10nd — APPROVED** [review]

**Pull request merged**
