### PR TITLE
Development of class Edgefx

### PR DESCRIPTION
**Pull request by krober10nd**
Development of mesh size function class Edgefx

### CODE REVIEW

**Review by WPringle — APPROVED** [review]
a lot of commits but doesn't seem like many changes. But seems like what is added is good.

**Comment by krober10nd** [comment]
Thanks, it's not done yet will take a few more weeks, but I"m having a rethink about the organization of things. 

These commits will get squashed and came mostly from the formation of the `geodata`

**Comment by krober10nd** [comment]
`edgefx`'s superclass `Grid` now has a `project` method which projects the values from one  `Grid` object onto another. For example. `Grid1` is projected onto `Grid2` only in the area of overlap between the two, elsewhere the values of `Grid2` are retained. (Note `Grid1` can also be projected onto `Grid2` but then the values of `Grid1` completely replace that out `Grid2`). 

```
from pyOceanMesh import *
 
grid1 = Grid(bbox=(0.0, 1.0, 0.0, 1.0), grid_spacing=0.1, values=10.0)
 
grid2 = Grid(bbox=(0.25, 0.50, 0.25, 0.50), grid_spacing=0.01, values=5.0)
 
grid3 = grid2.project(grid1)
 
grid3.plot()
```
test_proj

**Comment by krober10nd** [comment]
also, the `values` field is used throughout to hold for instance mesh sizes (or other scalar fields). If it's scalar then it's projected onto the size of the grid otherwise the size of values must match that of the grid.

**Comment by krober10nd** [comment]
Check this out....building two distance sizing functions then projecting them onto each other. 
Figure_1
 

```
 from oceanmesh import Shoreline, distance_sizing_function
 
 fname = "tests/GSHHS_l_L1.shp"
 
 
 bbox1 = (-75.0, -70.0, 38.0, 42.0)
 shore1 = Shoreline(fname, bbox1, 1000.0)
 
 dis1 = distance_sizing_function(shore1)
 ax = dis1.plot(hold=True)
 shore1.plot(ax)
 
 bbox2 = (-74.0, -73.0, 40.0, 41.0)
 shore2 = Shoreline(fname, bbox2, 100.0)
 
 dis2 = distance_sizing_function(shore2)
 ax = dis2.plot(hold=True)
 shore2.plot(ax)
 
 dis3 = dis2.project(dis1)
 
 ax = dis3.plot(hold=True)
 shore1.plot(ax)
```

**Pull request merged**
