### PR TITLE
meshing in map projections

### PR DESCRIPTION
**Pull request by krober10nd**
* Deprecate :class:`geodata` for :class:`Region`. This class becomes the parent for both `Shoreline` and `Grid` which hold vector and raster data, respectively. 
* A `Region` has an extent and crs (coordinate reference system), it can also be `transform_to` another projected space
```
 EPSG = 4326 # ESPG code for WGS84 which is what the geospatial data is in
 region = om.Region(extent=(-75.000, -70.001, 40.0001, 41.9000), crs=EPSG)
 region = region.transform_to(3857) # psuedo-Mercator for instance
 print(region.bbox)
```
* The idea here is simple, the user is consistent with the projected space extents and the units of the edge length. Mesh generation occurs in the projected space with no back-and-forth between different spaces. 
* Still to do:

- [x] improve `transform_to` method for both vector and raster datasets so heterogeneous datasets can be used to make sizing functions automatically in the user's desired coordinate system.
- [x] Calculate edge lengths in projected system during mesh generation. 
- [x] Unknown unknowns

### CODE REVIEW

**Comment by krober10nd** [comment]
@stefanzieger could you provide the .shx, .dbf, .prj files for the Shapefiles you used in tests you've created? I've made this more strict as now I'm adding the ability to build mesh size functions and inevitably mesh in a user-defined map projection. Thanks.

**Comment by krober10nd** [comment]
If the mesh is built in a map projection, then the edge length is just the L2 norm of the two sides of the edge.

 I don't see too much of a problem with this because edge lengths are typically < 10 km which is relatively short for large distortions.

**Comment by krober10nd** [comment]
Note, there are no more wild print statements. 

You can turn on logging to (by default) stdout like this at the top of your script:

```
 import logging
 import sys
 
logging.basicConfig(stream=sys.stdout, level=logging.WARNING)
# logging.basicConfig(stream=sys.stdout, level=logging.INFO)
# logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
```

**Comment by WPringle** [comment]
I think this will be good to go to merge in, once we get those `.shx,.dpf,.prj` shapefiles for the `test_rect.py` and `test_circ.py` tests from @stefanzieger

**Review by WPringle — APPROVED** [review]
Yep the tests all passed. Looks good.

**Pull request merged**
