### PR TITLE
add function to remove elements from a mesh using a mask

### PR DESCRIPTION
**Pull request by tomas19**

### CODE REVIEW

**Comment by tomas19** [comment]
I added a new Python script, ```oceanmesh/subset_fort14.py```. It contains 11 functions, but for doing the subset of a fort.14 you only need to call ```fort14Subset```. This last function calls the rest. I didn't provide a conda yml file, but the versions of the main packages are:

- Pandas version: 1.4.3
- Numpy version: 1.24.3
- Rtree version: 1.0.1
- Matplotlib version: 3.7.1
- Geopandas version: 0.13.0
- Shapely version: 2.0.1

The workflow follows the next steps:<br>
- Reads the original **fort.14** nodes as a dataframe with ```readNodes_fort14```
- Reads the mask **shapefile** as a geopandas GeoDataFrame with ```reaSubDomain``` (polygon covering the area we want to remove)
- Removes the elements with centroid inside the mask and renumber the nodes with ```subsetMeshGdf```
- Reads the boundary conditions of the original **fort.14** file with ```readBCfort14```
- Renumber the ocean boundary nodes with ```renumOceanBC```
- Renumber the closed land boundary (islands) nodes with ```renumClosedBCs```
- Renumber the mainland boundary nodes with ```renumMainlandBC```
- Writes the new fort.14 with ```writeFort14```

Thanks, Tomas

**Comment by krober10nd** [comment]
Hi Tomas, could you please rebase with the latest master branch before we start testing things?

**Comment by krober10nd** [comment]
One high level suggestion, not everyone knows what a "fort14" file is. Perhaps it makes sense to name these functions with the word "mesh" since they perform operations on a mesh?

**Comment by tomas19** [comment]
Done! I opened a new pull request with the updated scripts, so I'll close this one.

**Pull request closed without merging**
